#!/bin/bash
if [ "$(whoami)" != "root" ]; then
	echo "not root, exiting"
	exit 1
fi

loglocation="/etc/syschanges/newinfo"

echo "lspci:

" > $loglocation
lspci >> $loglocation
echo "lsblk:

" >> $loglocation
lsblk >> $loglocation
echo "lscpu:

" >> $loglocation
lscpu >> $loglocation # This often returns values because of CPU scaling, this is not usualy a security issue.
echo "lsinitramfs:

" >> $loglocation
lsinitramfs /boot/initrd.img-$(uname --kernel-release) >> $loglocation

echo "System changes: "

diff /etc/syschanges/newinfo /etc/syschanges/current
